version: "3"

networks:
  nginx-network:
    driver: bridge
  db-network:
    driver: bridge

services:
  db:
    container_name: db
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    networks:
      - db-network

  app:
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: teachercan
    env_file:
      - .env
    volumes:
      - ./app:/app/app
    command: uvicorn app.main:app --host 0.0.0.0 --reload
    networks:
      - nginx-network
      - db-network
    depends_on:
      - db

  admin:
    container_name: admin
    build:
      context: .
      dockerfile: Dockerfile
    image: teachercan-admin
    env_file:
      - .env
    volumes:
      - ./config:/app/config
      - ./teachercan:/app/teachercan
    command: python manage.py runserver 0.0.0.0:8000
    networks:
      - nginx-network
      - db-network
    depends_on:
      - db
      
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - app
      - admin
      - db
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # - static:/code/static
    networks:
      - nginx-network

volumes:
  postgres_data:
