version: "3"

networks:
  nginx-network:
    driver: bridge

services:

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    image: teachercan
    env_file:
      - .env
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
    command: uvicorn app.main:app --host 0.0.0.0
    networks:
      - nginx-network

  admin:
    container_name: admin
    build:
      context: .
      dockerfile: Dockerfile
    image: teachercan-admin
    env_file:
      - .env
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
    command: python manage.py runserver 0.0.0.0:8000
    networks:
      - nginx-network
      
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - app
      - admin
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # - static:/code/static
    networks:
      - nginx-network