[tool.poetry]
name = "teachercan-back"
version = "0.1.0"
description = "TeacherCan Renewal"
authors = ["Junbo Koh <cjsn92@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
django = "^4.2"
djangorestframework = "^3.14.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
