# Generated by Django 4.2.4 on 2024-03-17 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student_lists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'allergy',
            },
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=20)),
                ('student_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student_lists.studentlist')),
            ],
            options={
                'db_table': 'student_list_column',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('number', models.IntegerField()),
                ('gender', models.CharField(choices=[('남', '남'), ('여', '여')], default='남', max_length=2)),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='StudentAllergyRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.allergy')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'db_table': 'student_allergy_set',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='allergy',
            field=models.ManyToManyField(through='students.StudentAllergyRelation', to='students.allergy'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_list',
            field=models.ForeignKey(db_column='list_id', on_delete=django.db.models.deletion.CASCADE, to='student_lists.studentlist'),
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.column')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'db_table': 'student_list_row',
            },
        ),
    ]
