# Generated by Django 5.0.2 on 2024-03-10 03:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='student_list',
            field=models.ForeignKey(db_column='list_id', on_delete=django.db.models.deletion.CASCADE, to='students.studentlist'),
        ),
        migrations.AddField(
            model_name='column',
            name='student_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.studentlist'),
        ),
    ]
