# Generated by Django 4.2 on 2023-04-30 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseuser',
            old_name='nickname',
            new_name='username',
        ),
    ]
