# Generated by Django 4.2.3 on 2023-07-08 06:18

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="nickname",
            field=models.CharField(
                db_index=True,
                help_text="닉네임을 입력해주세요. 문자, 숫자, 특수문자는 @/./+/-/_ 만 가능합니다.",
                max_length=50,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name="nickname",
            ),
        ),
    ]
