# Generated by Django 4.2 on 2023-06-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email_alter_user_nickname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='area_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_sgv',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_male',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='school_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='school_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
