# Generated by Django 4.2.4 on 2023-08-23 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_school_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StudentList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('number', models.IntegerField()),
                ('is_male', models.BooleanField()),
                ('description', models.TextField()),
                ('allergy', models.ManyToManyField(db_column='allergy_code', to='users.allergy')),
                ('student_list', models.ForeignKey(db_column='list_id', on_delete=django.db.models.deletion.CASCADE, to='users.studentlist')),
            ],
        ),
    ]
