# Generated by Django 4.2.2 on 2023-07-01 15:16

import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_email_alter_user_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('area_code', models.CharField(max_length=10)),
                ('school_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='area_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='school_name',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(db_index=True, error_messages={'unique': '해당 아이디는 다른 사람이 사용중입니다.'}, help_text='아이디를 입력해주세요. 문자, 숫자, 특수문자는 @/./+/-/_ 만 가능합니다.', max_length=50, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()], verbose_name='user id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='school_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.school'),
        ),
    ]
