# Generated by Django 4.2.4 on 2023-08-25 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_allergy_studentlist_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlist',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='number',
            field=models.IntegerField(unique=True),
        ),
    ]
