# Generated by Django 4.2.4 on 2023-08-28 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_studentlist_is_main_alter_student_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
