# Generated by Django 4.2.2 on 2023-07-02 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_school_code_school_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='school_code',
            new_name='school',
        ),
    ]
