# Generated by Django 4.2.4 on 2023-11-29 15:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='column',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
