# Generated by Django 4.2.4 on 2024-01-06 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_column_created_at_column_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlist',
            name='discription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentlist',
            name='has_allergy',
            field=models.BooleanField(default=False),
        ),
    ]
