# Generated by Django 4.2.4 on 2024-01-06 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_studentlist_discription_studentlist_has_allergy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentlist',
            old_name='discription',
            new_name='description',
        ),
    ]
