# Generated by Django 5.0.2 on 2024-03-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('code', models.CharField(db_index=True, max_length=10, primary_key=True, serialize=False)),
                ('area_code', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'school',
            },
        ),
    ]
